### ISSUE TITLE
nginx 502 / "113: No route to host"

### ISSUE THREAD

**Issue by jpvalery** [chsasank/outline-wiki-docker-compose#31]
Hi everyone,

Thanks for the great work with this. I'm running into this issue as well.

cloned this repo and just made an edit to the docker-compose.yml to use tobi312/minio as I'm trying to run this on a Raspberry pi 4.

<img width="373" alt="image" src="https://user-images.githubusercontent.com/4112343/134816137-958b8f8c-6ac7-4716-9899-fac353acf5c0.png">

Here's my terminal output:
![Capture d’écran, le 2021-09-26 à 12 35 07](https://user-images.githubusercontent.com/4112343/134816253-7b486b2e-25ad-45b8-8671-c2a2d74d665d.png)

and my docker-compose.yml:
```
version: "3"
services:
  redis:
    image: redis
    restart: always
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: outline
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    restart: always
  minio:
    image: tobi312/minio
    volumes:
      - ./data/minio_root:/minio_root:z
      - ./data/certs:/root/.minio/certs:z
    command: "minio server /minio_root"
    env_file: ./env.minio
    restart: always
  outline:
    image: outlinewiki/outline:latest
    command: sh -c "yarn sequelize:migrate --env production-ssl-disabled && yarn start"
    environment:
      - DATABASE_URL=postgres://user:pass@postgres:5432/outline
      - DATABASE_URL_TEST=postgres://user:pass@postgres:5432/outline-test
      - REDIS_URL=redis://redis:6379
    env_file:
      - ./env.outline
      - ./env.slack
    restart: always
    depends_on:
      - postgres
      - redis
      - minio
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/nginx/:/etc/nginx/conf.d/:z
      - ./data/certs/:/etc/ssl/certs/:z
    restart: always
    depends_on:
      - outline
```

Checking the logs for the nginx container:
```
2021/09/26 23:55:22 [error] 31#31: *1 connect() failed (113: No route to host) while connecting to upstream, client: 172.19.0.1, server: , request: "GET / HTTP/2.0", upstream: "http://172.19.0.3:3000/", host: "pi4.local"
172.19.0.1 - - [26/Sep/2021:23:55:22 +0000] "GET / HTTP/2.0" 502 157 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:92.0) Gecko/20100101 Firefox/92.0" "-"
172.19.0.1 - - [26/Sep/2021:23:55:22 +0000] "GET /favicon.ico HTTP/2.0" 499 0 "https://pi4.local/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:92.0) Gecko/20100101 Firefox/92.0" "-"
```

Anybody ran into this before? Any suggestions? 

Thanks in advance for your help,
