### ISSUE TITLE
How to use own reverse proxy as traefik ?

### ISSUE THREAD

**Issue by anhhtca** [chsasank/outline-wiki-docker-compose#33]
Hello,

How can I run Outline behind a Traefik reverse proxy ?

`[Outline wiki:3000] <-> Traefik reverse proxy (domain_com:443)`

Or I just want to run Outline at any port (ex: 3000): `http://IP_ADDRESS:3000`

Thanks !

**Comment by Hansanghyeon** [comment]
@anhhtca I use traefik config

```yaml
services:
  minio:
    image: minio/minio
    volumes:
      - ./data/minio_root:/minio_root:z
      - ./data/certs:/root/.minio/certs:z
    env_file:
      - ./.env
      - ./.env.minio

    command: "minio server /minio_root"
    # command: server /data --console-address ":9001"
    deploy:
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
      labels:
        - traefik.enable=true
        - traefik.http.routers.minio-api.entrypoints=websecure
        - traefik.http.routers.minio-api.rule=Host(`wiki.beeclover.pro`) &&
          PathPrefix("/outline-bucket")
        - traefik.http.routers.minio-api.tls.certresolver=leresolver
        - traefik.http.routers.minio-api.service=minio-api-service
        - traefik.http.services.minio-api-service.loadbalancer.server.port=9000

  outline:
    image: outlinewiki/outline:latest
    command: sh -c "yarn sequelize:migrate --env production-ssl-disabled && yarn start"
    environment:
      - DATABASE_URL=postgres://postgres:${POSTGRESQL_PASSWORD}@DB_postgres:5432/wiki
      - REDIS_URL=redis://WORK-wiki_redis:6379
    env_file:
      - ./.env
      - ./.env.outline
      - ./.env.slack
    deploy:
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
      labels:
        - traefik.enable=true
        ## HTTP Routers
        - traefik.http.routers.202112__wiki.entrypoints=websecure
        - traefik.http.routers.202112__wiki.rule=Host(`wiki.beeclover.pro`)
        - traefik.http.routers.202112__wiki.tls.certresolver=leresolver
        - traefik.http.services.202112__wiki.loadbalancer.server.port=3000
  redis:
    image: redis
    volumes:
      - redis:/data
    deploy:
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
```

You can write to the Docker-Compose that is used by SWARM.

reference

- https://github.com/beeclover/wiki
